# Generated by Django 5.2.8 on 2025-12-24 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_course_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='courses',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'student'}, related_name='students', to='core.course'),
        ),
    ]
