# Generated by Django 5.2.8 on 2025-12-25 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_user_courses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assesment',
            name='name',
            field=models.CharField(choices=[('midterm', 'Midterm'), ('project', 'Project'), ('final', 'Final'), ('assingment', 'Assignment')], default='midterm', max_length=20),
        ),
    ]
