# Generated by Django 5.2.8 on 2025-12-27 13:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_assesment_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAssessmentScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('assesment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_scores', to='core.assesment')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('student', 'assesment')},
            },
        ),
    ]
