# Generated by Django 5.2.8 on 2025-11-16 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assesment',
            name='learning_outcome',
        ),
        migrations.RemoveField(
            model_name='assesment',
            name='weight',
        ),
        migrations.CreateModel(
            name='AssessmentLearningOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=1, help_text='Weight from 1 (lowest) to 5 (highest)')),
                ('assesment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.assesment')),
                ('learning_outcome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.learningoutcome')),
            ],
        ),
        migrations.AddField(
            model_name='assesment',
            name='learning_outcomes',
            field=models.ManyToManyField(related_name='assessments', through='core.AssessmentLearningOutcome', to='core.learningoutcome'),
        ),
    ]
