# Generated by Django 5.2.8 on 2025-11-16 08:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_assesment_learning_outcome_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learningoutcome',
            name='program_outcome',
        ),
        migrations.RemoveField(
            model_name='learningoutcome',
            name='weight',
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses_created', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='assesment',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assesments', to='core.course'),
        ),
        migrations.AddField(
            model_name='learningoutcome',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='learning_outcomes', to='core.course'),
        ),
        migrations.CreateModel(
            name='ProgramLearningOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=1, help_text='Weight from 1 (lowest) to 5 (highest)')),
                ('learning_outcome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.learningoutcome')),
                ('program_outcome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.programoutcome')),
            ],
        ),
        migrations.AddField(
            model_name='learningoutcome',
            name='program_outcomes',
            field=models.ManyToManyField(related_name='learning_outcomes', through='core.ProgramLearningOutcome', to='core.programoutcome'),
        ),
    ]
